# -*- coding: utf-8 -*-
"""
Latviešu uzvednes (prompts) priekš spēles.
Katrā raundā katrs spēlētājs saņem 2 uzvednes, katru uzvedni atbild 2 spēlētāji.
Vari brīvi pievienot savas — vienkārši ieraksti jaunu rindu sarakstā.
"""

PROMPTS = [
    "Sliktākais vārds, ko dot jaunam kaķēnam",
    "Vieta, kur nekad nevajadzētu rīkot kāzas",
    "Sliktākais veids, kā sākt sarunu ar svešinieku",
    "Ko nekad nevajadzētu teikt darba intervijā",
    "Slepenā sastāvdaļa, kas sabojā jebkuru ēdienu",
    "Visnepiemērotākā dāvana bērna dzimšanas dienā",
    "Aplams padoms, ko dot pirmklasniekam pirmajā skolas dienā",
    "Jauna Netflix seriāla nosaukums, kas garantēti izgāzīsies",
    "Sliktākais superspēks, kādu varētu iegūt",
    "Ko atrast savā kabatā un nožēlot",
    "Nepareizākais veids, kā atvadīties no viesiem",
    "Visdīvainākais iemesls kavēt lekciju",
    "Slikta ideja tetovējumam uz pieres",
    "Ko darīt, ja liftā paliec iestrēdzis ar priekšnieku",
    "Jaunas smaržas nosaukums, kas nevienu nepiesaistīs",
    "Sliktākais moto sporta komandai",
    "Ko nekad neteikt zobārstam, kamēr viņš strādā",
    "Visneveiksmīgākā ideja pirmajam randiņam",
    "Aizliegtais vārds, ko nedrīkst teikt ģimenes vakariņās",
    "Sliktākā motivējošā runa pirms eksāmena",
    "Dīvaina lieta, ko kolekcionēt slepenībā",
    "Ko rakstīt uz sava kapa akmens, lai visi pasmietos",
    "Visbezjēdzīgākais jauns mobilās lietotnes solījums",
    "Sliktākais veids, kā pieteikt mīlestību",
    "Ko darīt, ja pamosties un esi kļuvis par savu skolotāju",
    "Visneparastākā prasme, ar ko lielīties CV",
    "Jaunas picas nosaukums, ko neviens nepasūtīs",
    "Sliktākais laiks nostrādāt savu joku",
    "Ko ieraudzīt kaimiņa pagalmā un satraukties",
    "Aplamākais veids, kā tērēt loterijas laimestu",
    "Sliktākā doma, kas ienāk prātā tieši pirms miega",
    "Ko teikt, lai garantēti sabojātu Ziemassvētku vakaru",
    "Visdīvainākais jautājums, ko uzdot pirmajā tikšanās reizē",
    "Slikts nosaukums jaunam bāram Vecrīgā",
    "Ko darīt, ja pēkšņi kļūsti neredzams uz vienu stundu",
    "Visneveiksmīgākā ballītes tēma pieaugušajiem",
    "Ko atrast uz galda pēc kārtīgas ballītes",
    "Sliktākais padoms, kā ietaupīt naudu students",
    "Jaunas grāmatas nosaukums, ko neviens nelasīs",
    "Ko teikt lidmašīnā, lai visi sāktu uztraukties",
    "Visnepiemērotākā dziesma kāzu pirmajai dejai",
    "Sliktākais iemesls, kāpēc nokavēt savas kāzas",
    "Ko darīt, ja tavs sunis pēkšņi sāk runāt latviski",
    "Visdīvainākā lieta, ko pasūtīt restorānā",
    "Slikta ideja jaunam nacionālajam svētku ēdienam",
    "Ko rakstīt automātiskajā atbildē uz e-pastu atvaļinājumā",
    "Visneveiksmīgākais veids, kā iepazīties ar partnera vecākiem",
    "Ko teikt policistam, lai situāciju padarītu vēl sliktāku",
    "Sliktākais talants, ko rādīt talantu šovā",
    "Jauna sporta veids, kas nekad neaizies plašumā",
    "Ko darīt, ja pamosties uz skatuves nezinot, kāpēc esi tur",
    "Visdīvainākais iemesls kļūt slavenam",
    "Sliktākā vieta, kur pazaudēt telefonu",
    "Ko ieraudzīt spogulī un tūlīt nožēlot",
    "Aplamākais padoms jaunajiem vecākiem",
    "Ko teikt lidostas drošības darbiniekam, lai tevi aizturētu",
    "Visneparastākā lieta, ko glabāt ledusskapī",
    "Sliktākais jauns Latvijas tūrisma sauklis",
    "Ko darīt garlaicīgā sanāksmē, lai visus sanervozētu",
    "Visdīvainākā supervaroņa vārda izvēle",
]
